### ISSUE TITLE
license also MIT?

### ISSUE THREAD

**Issue by LifeCANvs** [floooh/qoiview#11]
Hi, does the MIT license also apply to this viewer (qoiview.c), as with qoi.h and the reference QOI encoder+decoder code?

**Comment by floooh** [comment]
Good point, yeah, since qoi.h is in the repository I guess it makes sense to also use the MIT license for the actual application code (the sokol headers are zlib/libpng which is even more liberal.

I'll add a MIT license.txt later today. Thanks for reminding me.

**Comment by LifeCANvs** [comment]
> Good point, yeah, since qoi.h is in the repository I guess it makes sense to also use the MIT license for the actual application code (the sokol headers are zlib/libpng which is even more liberal.
> 
> I'll add a MIT license.txt later today. Thanks for reminding me.

Cool, thanks :)
