### ISSUE TITLE
cannot open file directly

### ISSUE THREAD

**Issue by walksanatora** [floooh/qoiview#7]
when running via command like you cannot `qoiview <image>` this is a small feature but i believe that this would make it alot easier to integrate into desktops as most of the time when you click a file and `open with . . .` it just runs `<program name> <file name>` this would make this program a bit easier to use

**Comment by floooh** [comment]
This is the limitation of the command line args parser lib that's used which expects all arguments to be key-value pairs.

So the syntax to directly open a file is:

```qoiview file=[path to file]```

**Comment by walksanatora** [comment]
thanks. that worked
